name: 'nba_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'nba_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  nba_analytics:
    # Staging models
    staging:
      +materialized: view
      +schema: staging

    # Intermediate models
    intermediate:
      +materialized: view
      +schema: intermediate

    # Marts models (final data products)
    marts:
      +materialized: table
      +schema: analytics

# Test configurations
tests:
  nba_analytics:
    +severity: error

# Documentation
docs-paths: ["docs"]

# Seeds
seeds:
  nba_analytics:
    +schema: seed_data
