version: 2

sources:
  - name: staging
    schema: staging
    description: Raw data from NBA API
    tables:
      - name: player_game_stats_raw
        description: Raw player game statistics from NBA API
        columns:
          - name: game_id
            description: Unique game identifier
          - name: player_id
            description: NBA player ID
          - name: team_id
            description: NBA team ID

      - name: team_game_stats_raw
        description: Raw team game statistics from NBA API
        columns:
          - name: game_id
            description: Unique game identifier
          - name: team_id
            description: NBA team ID
          - name: game_date
            description: Date of the game
